name: Issue response
permissions:
  issues: write
on:
  issues:
    types:
      - opened
jobs:
  respond-to-issue:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' && github.actor != 'githubactions[bot]' && github.actor != 'octokitbot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine issue or PR number
        id: extract
        run: |
          echo "NUMBER=${{ github.event.issue.number }}" >> "$GITHUB_OUTPUT"
          mkdir results
          curl https://api.cloudflare.com/client/v4/accounts/ca379c37f08d428f2cf2247540b833d3/ai/run/@cf/stabilityai/stable-diffusion-xl-base-1.0 \
          -X POST -H "Authorization: Bearer ${{ secrets.CF_TOKEN }}" \
          -d '{ "prompt": "${{ github.event.issue.title }} ${{ github.event.issue.body }}" }' > results/result_${{ github.event.issue.number }}.png
      - name: Cache image
        id: cache-image
        uses: actions/cache@v4
        with:
          path: results/result_${{ steps.extract.outputs.NUMBER }}.png
          key: ${{ runner.os }}-result

      - name: Commit
        uses: wranders/commit-action@v0
        with:
          message: add image
          files: |
            results/result_${{ steps.extract.outputs.NUMBER }}.png

      - name: Respond to issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.extract.outputs.NUMBER }}
          body: >
            👋 Hi! Thank you for this input! Thank you & happy coding! 🚀
            ![result](results/result_${{ steps.extract.outputs.NUMBER }}.png)
